### ISSUE TITLE
error during generation

### ISSUE THREAD

**Issue by orgw** [jostorge/diffusion-hopping#2]
Hi!
*** Open Babel Warning  in PerceiveBondOrders
  Failed to kekulize aromatic bonds in OBMol::PerceiveBondOrders (title is 7s1s.pdb)
RuntimeError: Reduce returned return code 127 when running 'reduce -Trim /tmp/7s1s_2_obabel.pdb > /tmp/7s1s_2_obabel_reduce_tmp.pdb'

happens during generation

**Comment by twidatalla** [comment]
Hello, 

I am dealing with this error as well. Is there a solution @orgw?

Best,
Talal

**Comment by jostorge** [comment]
Hello,

not exactly sure how @orgw fixed the problem, but I might be able to point you into the right direction. 

I assume the error is thrown here:
https://github.com/jostorge/diffusion-hopping/blob/94aaca24339d021cf78b90c0ca18294b531b5766/diffusion_hopping/data/transform/reduce.py#L16-L19

the `reduce` binary returns non-zero exit codes even when everything is working fine when using the option `-Trim`, which is confusing. In the environments I used, it tended to return 255, which is hardcoded as the expected return code:
https://github.com/jostorge/diffusion-hopping/blob/94aaca24339d021cf78b90c0ca18294b531b5766/diffusion_hopping/data/transform/reduce.py#L21-L27

It looks like on your system this number might be 127 instead of 255 ($2^7 - 1$ instead of $2^8 - 1$). The general exit code behaviour of `reduce` is not clear to me, thus I can't provide a general solution.

However, for your specific case, it is probably sufficient to manually edit the following lines to 127 instead.
https://github.com/jostorge/diffusion-hopping/blob/94aaca24339d021cf78b90c0ca18294b531b5766/diffusion_hopping/data/transform/reduce.py#L24-L25

**Comment by twidatalla** [comment]
Apologies Jos, 

When I added my comment I hadn't realized I didn't have reduce installed, didn't catch that instruction in the README till after, I'm assuming this was @orgw's issue as well given we had the same exit code.

Best,
Talal
